[settings]
experimental = true
python.uv_venv_auto = true

[tools]
bat = "latest"
bat-extras = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gitui = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
uv = "latest"
zoxide = "latest"
yt-dlp = "latest"
"pipx:ranger-fm" = { version = "latest", uvx_args = "--with pillow" }
"pipx:black" = "latest"
tmux = "latest"

