[settings]
experimental = true
python.uv_venv_auto = true

[tools]
cargo-binstall = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gitui = "latest"
lazygit = "latest"
ripgrep = "latest"
ruff = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
yt-dlp = "latest"
zoxide = "latest"
"cargo:rmpc" = "latest"
"pipx:httpie" = "latest"
"pipx:ramalama" = "latest"
"pipx:smassh" = "latest"
"pipx:spotify-to-ytmusic" = "latest"
"pipx:git+https://github.com/ranger/ranger.git" = { version = "master", uvx_args = "--with pillow" }
"pipx:git+https://github.com/nathom/streamrip.git" = "dev"
"pipx:git+https://github.com/Diaoul/subliminal.git" = "latest"
python = "3.13.2"
