general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 180   # 3 mins
  on-timeout = brillo -O && brillo -u 20000000 -S 10
  on-resume = pkill brillo; brillo -u 2000000 -I
}

listener {
  timeout = 210   # 3.5 mins
  on-timeout = loginctl lock-session
}

listener {
  timeout = 240   # 4 mins
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 1200  # 20 mins
  on-timeout = systemctl suspend
}
